export const SEED_PRODUCTS = [
  // Electronics - 20 products
  {
    title: "Premium Wireless Noise-Cancelling Headphones",
    description: "Experience crystal-clear audio with industry-leading active noise cancellation. Features 30-hour battery life, premium leather ear cups, and seamless Bluetooth connectivity for work and entertainment.",
    category: "Electronics",
    subcategory: "Headphones",
    brand: "AudioTech Pro",
    imageUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&h=800&fit=crop&q=80",
    price: "249.99",
    originalPrice: "299.99",
    currency: "GBP",
    rating: "4.8",
    reviewCount: 2847,
    availability: "in_stock",
    stockQuantity: 45,
    features: ["Active Noise Cancellation", "30-hour battery", "Bluetooth 5.0", "Premium leather design", "Built-in microphone"],
    isFeatured: true,
  },
  {
    title: "Compact Bluetooth Wireless Earbuds",
    description: "True wireless freedom with compact earbuds featuring 8-hour battery per charge and premium sound quality. Includes protective charging case and water resistance for active lifestyles.",
    category: "Electronics",
    subcategory: "Headphones",
    brand: "SoundWave",
    imageUrl: "https://images.unsplash.com/photo-1583394838336-d2f0eee6e2c0?w=800&h=800&fit=crop&q=80",
    price: "89.99",
    originalPrice: "109.99",
    currency: "GBP",
    rating: "4.5",
    reviewCount: 1523,
    availability: "in_stock",
    stockQuantity: 120,
    features: ["True wireless", "8-hour battery", "Water resistant", "Touch controls", "Compact design"],
    isFeatured: false,
  },
  {
    title: "Studio Monitor Headphones for Professionals",
    description: "Professional-grade headphones with flat frequency response for accurate audio monitoring. Perfect for music production, podcasting, and critical listening with detachable cables.",
    category: "Electronics",
    subcategory: "Headphones",
    brand: "ProAudio",
    imageUrl: "https://images.unsplash.com/photo-1484704849700-f032a568e944?w=800&h=800&fit=crop&q=80",
    price: "179.99",
    originalPrice: "229.99",
    currency: "GBP",
    rating: "4.7",
    reviewCount: 892,
    availability: "in_stock",
    stockQuantity: 32,
    features: ["Flat frequency response", "Detachable cables", "Comfortable padding", "Swiveling ear cups", "35mm jack"],
    isFeatured: false,
  },
  {
    title: "Ultra-Thin Laptop 13-inch FHD Display",
    description: "Lightweight and powerful laptop featuring a stunning 13-inch FHD display, Intel Core i7 processor, and 16GB RAM. Perfect for professionals and students who demand portability without sacrificing performance.",
    category: "Electronics",
    subcategory: "Laptops",
    brand: "TechPro",
    imageUrl: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&h=800&fit=crop&q=80",
    price: "899.99",
    originalPrice: "1099.99",
    currency: "GBP",
    rating: "4.6",
    reviewCount: 1456,
    availability: "in_stock",
    stockQuantity: 18,
    features: ["Intel Core i7", "16GB RAM", "512GB SSD", "13-hour battery", "Lightweight design"],
    isFeatured: true,
  },
  {
    title: "High-Performance 15-inch Gaming Laptop",
    description: "Unleash your gaming potential with RTX graphics, 16GB RAM, and high-refresh-rate display. Built for serious gamers and content creators with advanced cooling system and RGB keyboard.",
    category: "Electronics",
    subcategory: "Laptops",
    brand: "GameForce",
    imageUrl: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&h=800&fit=crop&q=80",
    price: "1499.99",
    originalPrice: "1799.99",
    currency: "GBP",
    rating: "4.7",
    reviewCount: 2103,
    availability: "low_stock",
    stockQuantity: 8,
    features: ["RTX Graphics", "165Hz display", "16GB RAM", "1TB SSD", "RGB keyboard"],
    isFeatured: true,
  },
  {
    title: "Portable Business Ultrabook",
    description: "Sleek and powerful ultrabook designed for business professionals. Features long battery life, secure fingerprint login, and lightweight aluminum chassis for easy mobility.",
    category: "Electronics",
    subcategory: "Laptops",
    brand: "BusinessTech",
    imageUrl: "https://images.unsplash.com/photo-1525547719351-1a256e1534e8?w=800&h=800&fit=crop&q=80",
    price: "1199.99",
    originalPrice: "1399.99",
    currency: "GBP",
    rating: "4.5",
    reviewCount: 834,
    availability: "in_stock",
    stockQuantity: 22,
    features: ["Intel Core i5", "8GB RAM", "256GB SSD", "15-hour battery", "Fingerprint security"],
    isFeatured: false,
  },
  {
    title: "5G Flagship Smartphone 256GB",
    description: "Latest generation 5G smartphone with advanced triple camera system, 120Hz display, and ultra-fast processor. Featuring innovative design and all-day battery performance.",
    category: "Electronics",
    subcategory: "Phones",
    brand: "PhoneMax",
    imageUrl: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa6?w=800&h=800&fit=crop&q=80",
    price: "799.99",
    originalPrice: "999.99",
    currency: "GBP",
    rating: "4.8",
    reviewCount: 3521,
    availability: "in_stock",
    stockQuantity: 67,
    features: ["5G connectivity", "Triple camera", "120Hz display", "512GB storage", "Fast charging"],
    isFeatured: true,
  },
  {
    title: "Compact Mid-Range Smartphone 128GB",
    description: "Reliable mid-range smartphone with excellent value for money. Features dual camera, vibrant AMOLED display, and reliable performance for everyday use.",
    category: "Electronics",
    subcategory: "Phones",
    brand: "ValuePhone",
    imageUrl: "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=800&h=800&fit=crop&q=80",
    price: "349.99",
    originalPrice: "429.99",
    currency: "GBP",
    rating: "4.3",
    reviewCount: 1847,
    availability: "in_stock",
    stockQuantity: 89,
    features: ["Dual camera", "AMOLED display", "All-day battery", "128GB storage", "3.5mm jack"],
    isFeatured: false,
  },
  {
    title: "Budget-Friendly Smartphone 64GB",
    description: "Perfect entry-level smartphone with solid performance and clean interface. Ideal for basic communication, social media, and everyday tasks with reliable battery life.",
    category: "Electronics",
    subcategory: "Phones",
    brand: "BasicPhone",
    imageUrl: "https://images.unsplash.com/photo-1580910051074-3eb694886f35?w=800&h=800&fit=crop&q=80",
    price: "199.99",
    originalPrice: "249.99",
    currency: "GBP",
    rating: "3.9",
    reviewCount: 956,
    availability: "in_stock",
    stockQuantity: 145,
    features: ["Dual camera", "5000mAh battery", "Fast charging", "Clean UI", "Expandable storage"],
    isFeatured: false,
  },
  {
    title: "10-inch Portable Tablet with Stylus",
    description: "Versatile tablet perfect for drawing, note-taking, and entertainment. Includes precision stylus, vibrant display, and lightweight design for creative professionals and students.",
    category: "Electronics",
    subcategory: "Tablet",
    brand: "TabArt",
    imageUrl: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&h=800&fit=crop&q=80",
    price: "599.99",
    originalPrice: "749.99",
    currency: "GBP",
    rating: "4.6",
    reviewCount: 1234,
    availability: "in_stock",
    stockQuantity: 34,
    features: ["10-inch display", "Stylus included", "128GB storage", "All-day battery", "Lightweight"],
    isFeatured: true,
  },
  {
    title: "8-inch Compact Learning Tablet for Kids",
    description: "Child-friendly tablet with parental controls, educational apps, and durable design. Features colorful display and age-appropriate content filtering for safe learning.",
    category: "Electronics",
    subcategory: "Tablet",
    brand: "KidTab",
    imageUrl: "https://images.unsplash.com/photo-1561154464-82e0cc5a8e3e?w=800&h=800&fit=crop&q=80",
    price: "189.99",
    originalPrice: "249.99",
    currency: "GBP",
    rating: "4.4",
    reviewCount: 678,
    availability: "in_stock",
    stockQuantity: 56,
    features: ["Parental controls", "Educational apps", "Durable design", "8-inch display", "64GB storage"],
    isFeatured: false,
  },
  {
    title: "Professional DSLR Camera 24MP",
    description: "Advanced DSLR camera with 24MP sensor, 4K video recording, and professional lens compatibility. Ideal for photographers and videographers with manual controls and weather sealing.",
    category: "Electronics",
    subcategory: "Camera",
    brand: "CameraMax",
    imageUrl: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&h=800&fit=crop&q=80",
    price: "1299.99",
    originalPrice: "1599.99",
    currency: "GBP",
    rating: "4.9",
    reviewCount: 845,
    availability: "in_stock",
    stockQuantity: 12,
    features: ["24MP sensor", "4K video", "Weather sealed", "Dual SD card slots", "Professional AF"],
    isFeatured: true,
  },
  {
    title: "Compact Mirrorless Camera with Kit Lens",
    description: "Lightweight and powerful mirrorless camera perfect for travel and everyday photography. Features silent shutter, fast autofocus, and compact form factor with kit lens included.",
    category: "Electronics",
    subcategory: "Camera",
    brand: "ProVision",
    imageUrl: "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800&h=800&fit=crop&q=80",
    price: "899.99",
    originalPrice: "1099.99",
    currency: "GBP",
    rating: "4.7",
    reviewCount: 567,
    availability: "in_stock",
    stockQuantity: 19,
    features: ["Mirrorless design", "Silent shutter", "Fast AF", "Kit lens included", "4K video"],
    isFeatured: false,
  },
  {
    title: "Powerful Bluetooth Speaker System",
    description: "Room-filling sound with deep bass and crystal-clear treble. Features wireless connectivity, water resistance, and up to 12-hour battery life perfect for indoor and outdoor use.",
    category: "Electronics",
    subcategory: "Speaker",
    brand: "SoundBlast",
    imageUrl: "https://images.unsplash.com/photo-1545454675-2e16f39e1654?w=800&h=800&fit=crop&q=80",
    price: "189.99",
    originalPrice: "249.99",
    currency: "GBP",
    rating: "4.6",
    reviewCount: 1456,
    availability: "in_stock",
    stockQuantity: 67,
    features: ["Bluetooth 5.0", "Water resistant", "12-hour battery", "Deep bass", "Portable design"],
    isFeatured: false,
  },
  {
    title: "Premium Home Audio Speaker Set",
    description: "Complete home audio system delivering premium sound quality for music and movies. Includes wireless setup, smart home integration, and elegant design that complements any décor.",
    category: "Electronics",
    subcategory: "Speaker",
    brand: "AudioHome",
    imageUrl: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&h=800&fit=crop&q=80",
    price: "599.99",
    originalPrice: "799.99",
    currency: "GBP",
    rating: "4.8",
    reviewCount: 892,
    availability: "in_stock",
    stockQuantity: 23,
    features: ["Smart home compatible", "Wireless setup", "Premium drivers", "Elegant design", "360-degree sound"],
    isFeatured: true,
  },
  {
    title: "Fitness Smartwatch with Heart Rate Monitor",
    description: "Advanced fitness tracking with real-time heart rate monitoring, GPS tracking, and multiple sport modes. Water-resistant design with week-long battery life for continuous health monitoring.",
    category: "Electronics",
    subcategory: "Smartwatch",
    brand: "FitTech",
    imageUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&h=800&fit=crop&q=80",
    price: "249.99",
    originalPrice: "329.99",
    currency: "GBP",
    rating: "4.7",
    reviewCount: 2341,
    availability: "in_stock",
    stockQuantity: 78,
    features: ["Heart rate monitor", "GPS tracking", "7-day battery", "Water resistant", "Sleep tracking"],
    isFeatured: true,
  },
  {
    title: "Premium Luxury Smartwatch",
    description: "Elegant smartwatch combining style with technology featuring premium materials, AMOLED display, and comprehensive health monitoring. Perfect for business professionals.",
    category: "Electronics",
    subcategory: "Smartwatch",
    brand: "LuxeWatch",
    imageUrl: "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=800&h=800&fit=crop&q=80",
    price: "449.99",
    originalPrice: "599.99",
    currency: "GBP",
    rating: "4.8",
    reviewCount: 1205,
    availability: "in_stock",
    stockQuantity: 34,
    features: ["AMOLED display", "Premium materials", "14-day battery", "Health monitoring", "Elegant design"],
    isFeatured: true,
  },
  {
    title: "Entry-Level Gaming Console Bundle",
    description: "Complete gaming setup with console, two controllers, and popular game titles. Perfect for casual gamers and families with extensive gaming library access.",
    category: "Electronics",
    subcategory: "Gaming",
    brand: "GameHub",
    imageUrl: "https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=800&h=800&fit=crop&q=80",
    price: "299.99",
    originalPrice: "399.99",
    currency: "GBP",
    rating: "4.5",
    reviewCount: 3456,
    availability: "in_stock",
    stockQuantity: 45,
    features: ["Two controllers", "Game titles included", "4K support", "Online gaming", "Large library"],
    isFeatured: false,
  },
  {
    title: "Professional Gaming Setup Bundle",
    description: "High-performance gaming console with advanced hardware, multiple games, and accessories. Designed for serious gamers demanding cutting-edge performance and graphics.",
    category: "Electronics",
    subcategory: "Gaming",
    brand: "ProGame",
    imageUrl: "https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?w=800&h=800&fit=crop&q=80",
    price: "499.99",
    originalPrice: "699.99",
    currency: "GBP",
    rating: "4.8",
    reviewCount: 2847,
    availability: "low_stock",
    stockQuantity: 12,
    features: ["Next-gen performance", "Ray tracing", "Fast loading", "Game Pass included", "Premium controls"],
    isFeatured: true,
  },

  // Fashion - 18 products
  {
    title: "Classic Slim-Fit Oxford Shirt",
    description: "Premium quality cotton oxford shirt in timeless design perfect for business and casual occasions. Features comfortable fit, durable fabric, and easy care maintenance for everyday wear.",
    category: "Fashion",
    subcategory: "Clothing",
    brand: "ClassicStyle",
    imageUrl: "https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=800&h=800&fit=crop&q=80",
    price: "49.99",
    originalPrice: "69.99",
    currency: "GBP",
    rating: "4.6",
    reviewCount: 1247,
    availability: "in_stock",
    stockQuantity: 156,
    features: ["100% cotton", "Easy care", "Comfortable fit", "Multiple colors", "All sizes available"],
    isFeatured: false,
  },
  {
    title: "Modern Casual Chinos Trousers",
    description: "Versatile chinos for both casual and smart-casual occasions. Features breathable fabric, perfect fit, and timeless style that works with any wardrobe.",
    category: "Fashion",
    subcategory: "Clothing",
    brand: "ModernWear",
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85f7e7?w=800&h=800&fit=crop&q=80",
    price: "59.99",
    originalPrice: "79.99",
    currency: "GBP",
    rating: "4.5",
    reviewCount: 892,
    availability: "in_stock",
    stockQuantity: 134,
    features: ["Breathable fabric", "Perfect fit", "Easy wash", "Multiple colors", "Comfortable"],
    isFeatured: false,
  },
  {
    title: "Premium Denim Jacket",
    description: "Classic denim jacket featuring premium quality fabric and timeless design. Perfect layering piece for any season with vintage appeal and durability.",
    category: "Fashion",
    subcategory: "Clothing",
    brand: "DenimCo",
    imageUrl: "https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?w=800&h=800&fit=crop&q=80",
    price: "89.99",
    originalPrice: "119.99",
    currency: "GBP",
    rating: "4.7",
    reviewCount: 1556,
    availability: "in_stock",
    stockQuantity: 89,
    features: ["Premium denim", "Vintage design", "Durable", "All sizes", "Classic style"],
    isFeatured: true,
  },
  {
    title: "Elegant Summer Dress Collection",
    description: "Flowing summer dress perfect for warm weather and casual occasions. Features breathable fabric, elegant design, and comfortable fit ideal for all-day wear.",
    category: "Fashion",
    subcategory: "Clothing",
    brand: "SummerStyle",
    imageUrl: "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=800&h=800&fit=crop&q=80",
    price: "69.99",
    originalPrice: "99.99",
    currency: "GBP",
    rating: "4.6",
    reviewCount: 1203,
    availability: "in_stock",
    stockQuantity: 124,
    features: ["Breathable fabric", "Elegant design", "Easy care", "Multiple colors", "Comfortable"],
    isFeatured: false,
  },
  {
    title: "Luxury Leather Chelsea Boots",
    description: "Premium leather Chelsea boots with elegant design and superior comfort. Perfect for formal occasions or upscale casual wear with durable construction.",
    category: "Fashion",
    subcategory: "Shoes",
    brand: "LuxeFootwear",
    imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=800&fit=crop&q=80",
    price: "179.99",
    originalPrice: "239.99",
    currency: "GBP",
    rating: "4.8",
    reviewCount: 678,
    availability: "in_stock",
    stockQuantity: 45,
    features: ["Premium leather", "Comfortable fit", "Elegant design", "Durable sole", "Professional look"],
    isFeatured: true,
  },
  {
    title: "Comfortable Everyday Athletic Sneakers",
    description: "Stylish and comfortable sneakers perfect for everyday wear and light activities. Features cushioned sole, breathable material, and modern design.",
    category: "Fashion",
    subcategory: "Shoes",
    brand: "SportStyle",
    imageUrl: "https://images.unsplash.com/photo-1460353581996-0a96894549fc?w=800&h=800&fit=crop&q=80",
    price: "79.99",
    originalPrice: "109.99",
    currency: "GBP",
    rating: "4.5",
    reviewCount: 2134,
    availability: "in_stock",
    stockQuantity: 167,
    features: ["Cushioned sole", "Breathable material", "Lightweight", "Modern design", "All sizes"],
    isFeatured: false,
  },
  {
    title: "Professional Running Shoes",
    description: "High-performance running shoes engineered for serious runners. Features advanced cushioning, responsive sole, and lightweight design for optimal performance.",
    category: "Fashion",
    subcategory: "Shoes",
    brand: "RunTech",
    imageUrl: "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800&h=800&fit=crop&q=80",
    price: "139.99",
    originalPrice: "189.99",
    currency: "GBP",
    rating: "4.7",
    reviewCount: 1567,
    availability: "in_stock",
    stockQuantity: 98,
    features: ["Advanced cushioning", "Responsive sole", "Lightweight", "Breathable mesh", "Performance fit"],
    isFeatured: false,
  },
  {
    title: "Elegant Silk Scarves Collection",
    description: "Luxurious silk scarves in multiple patterns and colors. Perfect accessory for elevating any outfit with premium quality and elegant design.",
    category: "Fashion",
    subcategory: "Accessories",
    brand: "SilkLux",
    imageUrl: "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=800&h=800&fit=crop&q=80",
    price: "49.99",
    originalPrice: "69.99",
    currency: "GBP",
    rating: "4.6",
    reviewCount: 845,
    availability: "in_stock",
    stockQuantity: 203,
    features: ["100% silk", "Multiple patterns", "Elegant design", "Lightweight", "Easy care"],
    isFeatured: false,
  },
  {
    title: "Premium Leather Belts for Men",
    description: "Classic leather belts offering timeless style and quality craftsmanship. Perfect for formal and casual occasions with durable construction.",
    category: "Fashion",
    subcategory: "Accessories",
    brand: "BeltCraft",
    imageUrl: "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800&h=800&fit=crop&q=80",
    price: "39.99",
    originalPrice: "59.99",
    currency: "GBP",
    rating: "4.5",
    reviewCount: 1023,
    availability: "in_stock",
    stockQuantity: 145,
    features: ["Premium leather", "Multiple colors", "All sizes", "Adjustable", "Durable"],
    isFeatured: false,
  },
  {
    title: "Luxury Leather Handbag",
    description: "Premium leather handbag combining style and functionality. Features spacious interior, quality hardware, and elegant design perfect for everyday use.",
    category: "Fashion",
    subcategory: "Bags",
    brand: "BagLux",
    imageUrl: "https://images.unsplash.com/photo-1548036328-c896f5c0895a?w=800&h=800&fit=crop&q=80",
    price: "299.99",
    originalPrice: "399.99",
    currency: "GBP",
    rating: "4.8",
    reviewCount: 456,
    availability: "in_stock",
    stockQuantity: 34,
    features: ["Premium leather", "Spacious interior", "Quality hardware", "Elegant design", "Durable"],
    isFeatured: true,
  },
  {
    title: "Professional Backpack for Work",
    description: "Versatile backpack perfect for commuting and business travel. Features multiple compartments, laptop pocket, and ergonomic design for comfortable carrying.",
    category: "Fashion",
    subcategory: "Bags",
    brand: "BackPro",
    imageUrl: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&h=800&fit=crop&q=80",
    price: "89.99",
    originalPrice: "129.99",
    currency: "GBP",
    rating: "4.6",
    reviewCount: 1234,
    availability: "in_stock",
    stockQuantity: 87,
    features: ["Laptop pocket", "Multiple compartments", "Ergonomic design", "Water resistant", "Comfortable"],
    isFeatured: false,
  },
  {
    title: "Stainless Steel Smartwatch Strap",
    description: "Premium stainless steel strap compatible with popular smartwatches. Features polished finish, secure closure, and sophisticated appearance for any occasion.",
    category: "Fashion",
    subcategory: "Accessories",
    brand: "StrapTech",
    imageUrl: "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800&h=800&fit=crop&q=80",
    price: "34.99",
    originalPrice: "49.99",
    currency: "GBP",
    rating: "4.5",
    reviewCount: 789,
    availability: "in_stock",
    stockQuantity: 234,
    features: ["Stainless steel", "Easy replacement", "Polished finish", "Secure closure", "Premium look"],
    isFeatured: false,
  },
  {
    title: "Cashmere Winter Sweater",
    description: "Ultra-soft cashmere sweater perfect for winter elegance. Features premium quality, comfortable fit, and timeless design for versatile styling.",
    category: "Fashion",
    subcategory: "Clothing",
    brand: "CashmereLux",
    imageUrl: "https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?w=800&h=800&fit=crop&q=80",
    price: "199.99",
    originalPrice: "279.99",
    currency: "GBP",
    rating: "4.8",
    reviewCount: 567,
    availability: "in_stock",
    stockQuantity: 45,
    features: ["100% cashmere", "Ultra-soft", "Premium quality", "Multiple colors", "Timeless design"],
    isFeatured: true,
  },
  {
    title: "Lightweight Wool Coat",
    description: "Elegant wool coat offering warmth without bulk. Perfect for transitional seasons with classic design and high-quality fabric.",
    category: "Fashion",
    subcategory: "Clothing",
    brand: "CoatStyle",
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85f7e7?w=800&h=800&fit=crop&q=80",
    price: "249.99",
    originalPrice: "349.99",
    currency: "GBP",
    rating: "4.7",
    reviewCount: 834,
    availability: "in_stock",
    stockQuantity: 56,
    features: ["Premium wool", "Lightweight", "Elegant design", "All sizes", "Easy care"],
    isFeatured: true,
  },
  {
    title: "High-Quality Denim Jeans",
    description: "Classic denim jeans with perfect fit and premium fabric. Versatile for casual and smart-casual occasions with timeless style.",
    category: "Fashion",
    subcategory: "Clothing",
    brand: "DenimMax",
    imageUrl: "https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=800&h=800&fit=crop&q=80",
    price: "74.99",
    originalPrice: "99.99",
    currency: "GBP",
    rating: "4.6",
    reviewCount: 2156,
    availability: "in_stock",
    stockQuantity: 178,
    features: ["Premium denim", "Perfect fit", "Durable", "Multiple sizes", "Easy wash"],
    isFeatured: false,
  },
  {
    title: "Designer Sunglasses Collection",
    description: "Stylish sunglasses featuring UV protection and premium frame design. Perfect for sunny days and fashion-forward looks.",
    category: "Fashion",
    subcategory: "Accessories",
    brand: "SunStyle",
    imageUrl: "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=800&h=800&fit=crop&q=80",
    price: "99.99",
    originalPrice: "149.99",
    currency: "GBP",
    rating: "4.7",
    reviewCount: 1345,
    availability: "in_stock",
    stockQuantity: 123,
    features: ["UV protection", "Premium frames", "Multiple styles", "Durable", "Fashionable"],
    isFeatured: false,
  },

  // Home & Kitchen - 18 products
  {
    title: "Premium Non-Stick Cookware Set",
    description: "Complete cookware set with non-stick coating for easy cooking and cleanup. Includes multiple pans and pots perfect for everyday cooking and meal preparation.",
    category: "Home & Kitchen",
    subcategory: "Cookware",
    brand: "CookPro",
    imageUrl: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&h=800&fit=crop&q=80",
    price: "129.99",
    originalPrice: "179.99",
    currency: "GBP",
    rating: "4.7",
    reviewCount: 1892,
    availability: "in_stock",
    stockQuantity: 67,
    features: ["Non-stick coating", "Complete set", "Durable handles", "Heat resistant", "Easy cleanup"],
    isFeatured: true,
  },
  {
    title: "Stainless Steel Professional Chef Knife",
    description: "High-quality chef knife with sharp blade and comfortable grip. Perfect for precise cutting and professional kitchen use with excellent balance.",
    category: "Home & Kitchen",
    subcategory: "Cookware",
    brand: "ChefKnife",
    imageUrl: "https://images.unsplash.com/photo-1556910585-09baa3a3b1f1?w=800&h=800&fit=crop&q=80",
    price: "49.99",
    originalPrice: "69.99",
    currency: "GBP",
    rating: "4.8",
    reviewCount: 1245,
    availability: "in_stock",
    stockQuantity: 156,
    features: ["Sharp blade", "Comfortable grip", "Stainless steel", "Professional grade", "Durable"],
    isFeatured: false,
  },
  {
    title: "Automated Coffee Maker with Timer",
    description: "Convenient coffee maker featuring programmable timer and automated brewing. Perfect for morning routines with large capacity and easy maintenance.",
    category: "Home & Kitchen",
    subcategory: "Appliances",
    brand: "CoffeePro",
    imageUrl: "https://images.unsplash.com/photo-1585515320310-259814833e62?w=800&h=800&fit=crop&q=80",
    price: "69.99",
    originalPrice: "99.99",
    currency: "GBP",
    rating: "4.5",
    reviewCount: 2341,
    availability: "in_stock",
    stockQuantity: 89,
    features: ["Programmable timer", "Large capacity", "Auto shutoff", "Easy cleanup", "Durable"],
    isFeatured: false,
  },
  {
    title: "Elegant Dining Table Set",
    description: "Premium dining table with matching chairs perfect for family meals. Features solid construction, elegant design, and spacious seating for six.",
    category: "Home & Kitchen",
    subcategory: "Furniture",
    brand: "FurniturePro",
    imageUrl: "https://images.unsplash.com/photo-1555041469-a586c28abd73?w=800&h=800&fit=crop&q=80",
    price: "599.99",
    originalPrice: "799.99",
    currency: "GBP",
    rating: "4.6",
    reviewCount: 567,
    availability: "low_stock",
    stockQuantity: 8,
    features: ["Solid construction", "Elegant design", "Seats 6", "Quality finish", "Durable wood"],
    isFeatured: true,
  },
  {
    title: "Comfortable Sectional Sofa",
    description: "Spacious sectional sofa perfect for large living rooms. Features comfortable seating, quality upholstery, and modular design for flexible arrangement.",
    category: "Home & Kitchen",
    subcategory: "Furniture",
    brand: "SofaMax",
    imageUrl: "https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=800&h=800&fit=crop&q=80",
    price: "899.99",
    originalPrice: "1199.99",
    currency: "GBP",
    rating: "4.7",
    reviewCount: 834,
    availability: "in_stock",
    stockQuantity: 12,
    features: ["Spacious design", "Quality upholstery", "Modular pieces", "Comfortable", "Durable"],
    isFeatured: true,
  },
  {
    title: "Modern Coffee Table",
    description: "Contemporary coffee table with sleek design and sturdy construction. Perfect complement to modern living rooms with practical storage.",
    category: "Home & Kitchen",
    subcategory: "Furniture",
    brand: "ModernHome",
    imageUrl: "https://images.unsplash.com/photo-1524758631624-e2822e304c0c?w=800&h=800&fit=crop&q=80",
    price: "199.99",
    originalPrice: "279.99",
    currency: "GBP",
    rating: "4.5",
    reviewCount: 456,
    availability: "in_stock",
    stockQuantity: 45,
    features: ["Modern design", "Sturdy construction", "Storage space", "Easy assembly", "Elegant finish"],
    isFeatured: false,
  },
  {
    title: "Decorative Wall Art Set",
    description: "Beautiful wall art collection perfect for interior decoration. Features premium frames, high-quality prints, and easy installation.",
    category: "Home & Kitchen",
    subcategory: "Decor",
    brand: "WallArt",
    imageUrl: "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&h=800&fit=crop&q=80",
    price: "129.99",
    originalPrice: "179.99",
    currency: "GBP",
    rating: "4.6",
    reviewCount: 789,
    availability: "in_stock",
    stockQuantity: 124,
    features: ["Premium frames", "High-quality prints", "Easy installation", "Multiple designs", "Stylish"],
    isFeatured: false,
  },
  {
    title: "Elegant Curtain Collection",
    description: "Premium curtains with thermal insulation and light-blocking properties. Perfect for bedrooms and living rooms with elegant designs.",
    category: "Home & Kitchen",
    subcategory: "Decor",
    brand: "CurtainStyle",
    imageUrl: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&h=800&fit=crop&q=80",
    price: "89.99",
    originalPrice: "129.99",
    currency: "GBP",
    rating: "4.5",
    reviewCount: 1023,
    availability: "in_stock",
    stockQuantity: 156,
    features: ["Thermal insulation", "Light blocking", "Elegant design", "Multiple colors", "Easy care"],
    isFeatured: false,
  },
  {
    title: "High-Power Blender Machine",
    description: "Powerful blender for smoothies, soups, and beverages. Features variable speed control, durable glass pitcher, and quiet operation.",
    category: "Home & Kitchen",
    subcategory: "Appliances",
    brand: "BlendMax",
    imageUrl: "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800&h=800&fit=crop&q=80",
    price: "129.99",
    originalPrice: "179.99",
    currency: "GBP",
    rating: "4.6",
    reviewCount: 1567,
    availability: "in_stock",
    stockQuantity: 78,
    features: ["Variable speed", "Glass pitcher", "Quiet operation", "Powerful motor", "Easy cleanup"],
    isFeatured: true,
  },
  {
    title: "Smart Microwave Oven",
    description: "Modern microwave with smart features and multiple cooking modes. Perfect for quick meal preparation with energy efficiency.",
    category: "Home & Kitchen",
    subcategory: "Appliances",
    brand: "SmartKitchen",
    imageUrl: "https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?w=800&h=800&fit=crop&q=80",
    price: "149.99",
    originalPrice: "199.99",
    currency: "GBP",
    rating: "4.5",
    reviewCount: 892,
    availability: "in_stock",
    stockQuantity: 67,
    features: ["Smart features", "Multiple modes", "Energy efficient", "Large capacity", "Easy controls"],
    isFeatured: false,
  },
  {
    title: "Elegant Bedding Set",
    description: "Premium bedding with soft fabrics and elegant design. Includes duvet, pillows, and sheets perfect for comfortable sleep.",
    category: "Home & Kitchen",
    subcategory: "Decor",
    brand: "BeddingLux",
    imageUrl: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&h=800&fit=crop&q=80",
    price: "199.99",
    originalPrice: "279.99",
    currency: "GBP",
    rating: "4.7",
    reviewCount: 1456,
    availability: "in_stock",
    stockQuantity: 98,
    features: ["Premium fabrics", "Elegant design", "Soft texture", "Multiple sizes", "Easy wash"],
    isFeatured: true,
  },
  {
    title: "Stainless Steel Trash Can",
    description: "Modern trash can with automatic sensor lid and fingerprint-resistant finish. Perfect for kitchens and bathrooms with sleek design.",
    category: "Home & Kitchen",
    subcategory: "Decor",
    brand: "TrashPro",
    imageUrl: "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&h=800&fit=crop&q=80",
    price: "79.99",
    originalPrice: "119.99",
    currency: "GBP",
    rating: "4.4",
    reviewCount: 567,
    availability: "in_stock",
    stockQuantity: 145,
    features: ["Auto sensor", "Fingerprint resistant", "Stainless steel", "Large capacity", "Sleek design"],
    isFeatured: false,
  },
  {
    title: "Luxury Bath Towel Set",
    description: "Premium cotton towels with soft texture and vibrant colors. Perfect for bathrooms with excellent durability and absorbency.",
    category: "Home & Kitchen",
    subcategory: "Decor",
    brand: "TowelLux",
    imageUrl: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&h=800&fit=crop&q=80",
    price: "59.99",
    originalPrice: "89.99",
    currency: "GBP",
    rating: "4.6",
    reviewCount: 1234,
    availability: "in_stock",
    stockQuantity: 189,
    features: ["Premium cotton", "Soft texture", "Vibrant colors", "Durable", "Absorbent"],
    isFeatured: false,
  },
  {
    title: "Portable Cooler Box",
    description: "Large capacity cooler perfect for outdoor activities and parties. Features excellent insulation and durable construction.",
    category: "Home & Kitchen",
    subcategory: "Decor",
    brand: "CoolerPro",
    imageUrl: "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&h=800&fit=crop&q=80",
    price: "89.99",
    originalPrice: "129.99",
    currency: "GBP",
    rating: "4.5",
    reviewCount: 845,
    availability: "in_stock",
    stockQuantity: 76,
    features: ["Large capacity", "Excellent insulation", "Durable", "Portable handles", "Weather resistant"],
    isFeatured: false,
  },
  {
    title: "Wireless Kitchen Scale",
    description: "Smart kitchen scale with precision measurement and digital display. Perfect for cooking and baking with app connectivity.",
    category: "Home & Kitchen",
    subcategory: "Cookware",
    brand: "ScaleMax",
    imageUrl: "https://images.unsplash.com/photo-1556910585-09baa3a3b1f1?w=800&h=800&fit=crop&q=80",
    price: "59.99",
    originalPrice: "79.99",
    currency: "GBP",
    rating: "4.6",
    reviewCount: 678,
    availability: "in_stock",
    stockQuantity: 112,
    features: ["Digital display", "Precision measurement", "App connectivity", "Wireless", "Durable"],
    isFeatured: false,
  },

  // Sports & Outdoors - 15 products
  {
    title: "Professional Yoga Mat with Carrier",
    description: "Premium yoga mat with non-slip surface and comfortable padding. Includes carrying strap for easy transport to classes and outdoor workouts.",
    category: "Sports & Outdoors",
    subcategory: "Fitness",
    brand: "YogaMax",
    imageUrl: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&h=800&fit=crop&q=80",
    price: "49.99",
    originalPrice: "69.99",
    currency: "GBP",
    rating: "4.7",
    reviewCount: 1567,
    availability: "in_stock",
    stockQuantity: 134,
    features: ["Non-slip surface", "Comfortable padding", "Carrying strap", "Premium material", "Durable"],
    isFeatured: false,
  },
  {
    title: "Adjustable Weight Dumbbell Set",
    description: "Complete dumbbell set with adjustable weights perfect for home workouts. Features comfortable grip and precise weight increments.",
    category: "Sports & Outdoors",
    subcategory: "Fitness",
    brand: "FitnessGear",
    imageUrl: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&h=800&fit=crop&q=80",
    price: "199.99",
    originalPrice: "279.99",
    currency: "GBP",
    rating: "4.8",
    reviewCount: 2143,
    availability: "in_stock",
    stockQuantity: 45,
    features: ["Adjustable weights", "Complete set", "Comfortable grip", "Home workout ready", "Durable"],
    isFeatured: true,
  },
  {
    title: "Resistance Training Bands Set",
    description: "Versatile resistance bands for strength training and physical therapy. Includes multiple resistance levels in convenient carrying bag.",
    category: "Sports & Outdoors",
    subcategory: "Fitness",
    brand: "ResistancePro",
    imageUrl: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&h=800&fit=crop&q=80",
    price: "39.99",
    originalPrice: "59.99",
    currency: "GBP",
    rating: "4.6",
    reviewCount: 1234,
    availability: "in_stock",
    stockQuantity: 156,
    features: ["Multiple resistance levels", "Carrying bag", "Versatile training", "Durable material", "Portable"],
    isFeatured: false,
  },
  {
    title: "Premium Camping Tent 4-Person",
    description: "Spacious camping tent with weatherproof design and easy setup. Perfect for family camping trips with excellent ventilation and durability.",
    category: "Sports & Outdoors",
    subcategory: "Camping",
    brand: "CampMax",
    imageUrl: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800&h=800&fit=crop&q=80",
    price: "149.99",
    originalPrice: "199.99",
    currency: "GBP",
    rating: "4.7",
    reviewCount: 892,
    availability: "in_stock",
    stockQuantity: 34,
    features: ["Weatherproof", "Easy setup", "Spacious", "Good ventilation", "Durable fabric"],
    isFeatured: true,
  },
  {
    title: "Lightweight Sleeping Bag",
    description: "Portable sleeping bag perfect for camping and outdoor adventures. Features temperature regulation and compact packing size.",
    category: "Sports & Outdoors",
    subcategory: "Camping",
    brand: "SleepGear",
    imageUrl: "https://images.unsplash.com/photo-1478827536114-da961b7f86d2?w=800&h=800&fit=crop&q=80",
    price: "79.99",
    originalPrice: "109.99",
    currency: "GBP",
    rating: "4.5",
    reviewCount: 678,
    availability: "in_stock",
    stockQuantity: 89,
    features: ["Temperature regulation", "Lightweight", "Compact packing", "Comfortable", "Water resistant"],
    isFeatured: false,
  },
  {
    title: "Professional Mountain Bike",
    description: "High-performance mountain bike with advanced suspension and durable frame. Perfect for off-road trails and adventurous riders.",
    category: "Sports & Outdoors",
    subcategory: "Cycling",
    brand: "BikeMax",
    imageUrl: "https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=800&h=800&fit=crop&q=80",
    price: "599.99",
    originalPrice: "799.99",
    currency: "GBP",
    rating: "4.8",
    reviewCount: 1245,
    availability: "in_stock",
    stockQuantity: 23,
    features: ["Advanced suspension", "Durable frame", "Off-road ready", "Precision gears", "High performance"],
    isFeatured: true,
  },
  {
    title: "Compact Road Bike",
    description: "Lightweight road bike designed for speed and efficiency. Features drop bars, thin tires, and precise gear system for long-distance cycling.",
    category: "Sports & Outdoors",
    subcategory: "Cycling",
    brand: "RoadPro",
    imageUrl: "https://images.unsplash.com/photo-1511994298241-608e28f14fde?w=800&h=800&fit=crop&q=80",
    price: "499.99",
    originalPrice: "699.99",
    currency: "GBP",
    rating: "4.7",
    reviewCount: 834,
    availability: "in_stock",
    stockQuantity: 34,
    features: ["Lightweight design", "Drop bars", "Thin tires", "Precise gears", "Long-distance ready"],
    isFeatured: false,
  },
  {
    title: "High-Performance Running Shoes",
    description: "Advanced running shoes with responsive cushioning and breathable material. Engineered for comfort during long-distance running.",
    category: "Sports & Outdoors",
    subcategory: "Running",
    brand: "RunnerMax",
    imageUrl: "https://images.unsplash.com/photo-1460353581996-0a96894549fc?w=800&h=800&fit=crop&q=80",
    price: "129.99",
    originalPrice: "179.99",
    currency: "GBP",
    rating: "4.7",
    reviewCount: 2156,
    availability: "in_stock",
    stockQuantity: 156,
    features: ["Responsive cushioning", "Breathable material", "Long-distance ready", "Lightweight", "Comfortable"],
    isFeatured: false,
  },
  {
    title: "Athletic Performance Watch",
    description: "Sports watch with GPS tracking and heart rate monitoring. Perfect for runners and athletes tracking performance metrics.",
    category: "Sports & Outdoors",
    subcategory: "Running",
    brand: "SportWatch",
    imageUrl: "https://images.unsplash.com/photo-1539185441755-769473a23570?w=800&h=800&fit=crop&q=80",
    price: "199.99",
    originalPrice: "279.99",
    currency: "GBP",
    rating: "4.6",
    reviewCount: 1345,
    availability: "in_stock",
    stockQuantity: 78,
    features: ["GPS tracking", "Heart rate monitor", "Performance metrics", "Water resistant", "Long battery"],
    isFeatured: true,
  },
  {
    title: "Protective Cycling Helmet",
    description: "Safety helmet with aerodynamic design and excellent ventilation. Perfect for road and mountain cycling with comfortable padding.",
    category: "Sports & Outdoors",
    subcategory: "Cycling",
    brand: "SafeGear",
    imageUrl: "https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=800&h=800&fit=crop&q=80",
    price: "89.99",
    originalPrice: "129.99",
    currency: "GBP",
    rating: "4.5",
    reviewCount: 1023,
    availability: "in_stock",
    stockQuantity: 134,
    features: ["Safety certified", "Aerodynamic design", "Good ventilation", "Comfortable padding", "Lightweight"],
    isFeatured: false,
  },
  {
    title: "Professional Tennis Racket",
    description: "High-performance tennis racket with optimal balance and power. Features advanced string technology for enhanced control and spin.",
    category: "Sports & Outdoors",
    subcategory: "Fitness",
    brand: "TennisMax",
    imageUrl: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&h=800&fit=crop&q=80",
    price: "179.99",
    originalPrice: "249.99",
    currency: "GBP",
    rating: "4.6",
    reviewCount: 567,
    availability: "in_stock",
    stockQuantity: 45,
    features: ["Optimal balance", "Advanced strings", "Enhanced control", "Professional grade", "Durable"],
    isFeatured: false,
  },
  {
    title: "Portable Water Bottle with Insulation",
    description: "Keep drinks cold or hot for hours with premium insulation. Lightweight and durable perfect for outdoor activities and sports.",
    category: "Sports & Outdoors",
    subcategory: "Camping",
    brand: "HydroMax",
    imageUrl: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800&h=800&fit=crop&q=80",
    price: "34.99",
    originalPrice: "49.99",
    currency: "GBP",
    rating: "4.7",
    reviewCount: 2234,
    availability: "in_stock",
    stockQuantity: 234,
    features: ["Premium insulation", "Lightweight", "Durable", "Temperature control", "Easy carry"],
    isFeatured: false,
  },
  {
    title: "Complete Camping Cookware Set",
    description: "Portable cooking set perfect for camping and outdoor meals. Includes pot, pan, and utensils with compact storage.",
    category: "Sports & Outdoors",
    subcategory: "Camping",
    brand: "CampKitchen",
    imageUrl: "https://images.unsplash.com/photo-1478827536114-da961b7f86d2?w=800&h=800&fit=crop&q=80",
    price: "59.99",
    originalPrice: "79.99",
    currency: "GBP",
    rating: "4.5",
    reviewCount: 789,
    availability: "in_stock",
    stockQuantity: 112,
    features: ["Portable design", "Complete set", "Durable material", "Easy storage", "Lightweight"],
    isFeatured: false,
  },

  // Beauty & Personal Care - 15 products
  {
    title: "Premium Anti-Aging Face Cream",
    description: "Advanced skincare cream with retinol and hyaluronic acid. Reduces wrinkles and improves skin texture for youthful radiance.",
    category: "Beauty & Personal Care",
    subcategory: "Skincare",
    brand: "SkinLux",
    imageUrl: "https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=800&h=800&fit=crop&q=80",
    price: "59.99",
    originalPrice: "79.99",
    currency: "GBP",
    rating: "4.7",
    reviewCount: 1567,
    availability: "in_stock",
    stockQuantity: 98,
    features: ["Retinol formula", "Hyaluronic acid", "Anti-wrinkle", "All skin types", "Premium quality"],
    isFeatured: true,
  },
  {
    title: "Gentle Cleansing Face Wash",
    description: "Mild cleanser perfect for daily facial cleansing. Removes impurities without stripping natural moisture from skin.",
    category: "Beauty & Personal Care",
    subcategory: "Skincare",
    brand: "CleanFace",
    imageUrl: "https://images.unsplash.com/photo-1570194065650-d99fb4bedf0a?w=800&h=800&fit=crop&q=80",
    price: "24.99",
    originalPrice: "34.99",
    currency: "GBP",
    rating: "4.5",
    reviewCount: 2145,
    availability: "in_stock",
    stockQuantity: 167,
    features: ["Gentle formula", "pH balanced", "No harsh chemicals", "Daily use", "All skin types"],
    isFeatured: false,
  },
  {
    title: "Moisturizing Facial Mask",
    description: "Hydrating mask providing deep moisture and nourishment. Perfect weekly treatment for dry and dehydrated skin.",
    category: "Beauty & Personal Care",
    subcategory: "Skincare",
    brand: "MaskCare",
    imageUrl: "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=800&h=800&fit=crop&q=80",
    price: "34.99",
    originalPrice: "49.99",
    currency: "GBP",
    rating: "4.6",
    reviewCount: 1023,
    availability: "in_stock",
    stockQuantity: 145,
    features: ["Deep moisture", "Weekly treatment", "Nourishing formula", "All skin types", "Soothing"],
    isFeatured: false,
  },
  {
    title: "Volumizing Shampoo for Fine Hair",
    description: "Lightweight shampoo specifically formulated for fine hair. Adds volume and thickness without weighing hair down.",
    category: "Beauty & Personal Care",
    subcategory: "Haircare",
    brand: "VolumePro",
    imageUrl: "https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?w=800&h=800&fit=crop&q=80",
    price: "19.99",
    originalPrice: "29.99",
    currency: "GBP",
    rating: "4.5",
    reviewCount: 1456,
    availability: "in_stock",
    stockQuantity: 189,
    features: ["Lightweight formula", "Volume enhancing", "Fine hair", "Daily use", "Gentle"],
    isFeatured: false,
  },
  {
    title: "Smoothing Hair Conditioner",
    description: "Nourishing conditioner that smooths frizz and adds shine. Perfect for all hair types with repairing formula.",
    category: "Beauty & Personal Care",
    subcategory: "Haircare",
    brand: "SmoothHair",
    imageUrl: "https://images.unsplash.com/photo-1522338242042-2d1bcbaafec0?w=800&h=800&fit=crop&q=80",
    price: "21.99",
    originalPrice: "31.99",
    currency: "GBP",
    rating: "4.6",
    reviewCount: 1234,
    availability: "in_stock",
    stockQuantity: 156,
    features: ["Smoothing action", "Frizz control", "Shine enhancing", "Repairing", "All hair types"],
    isFeatured: false,
  },
  {
    title: "Professional Makeup Brush Set",
    description: "Complete brush set for makeup application. Features high-quality bristles and ergonomic handles for precision.",
    category: "Beauty & Personal Care",
    subcategory: "Makeup",
    brand: "MakeupPro",
    imageUrl: "https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=800&h=800&fit=crop&q=80",
    price: "49.99",
    originalPrice: "69.99",
    currency: "GBP",
    rating: "4.7",
    reviewCount: 892,
    availability: "in_stock",
    stockQuantity: 78,
    features: ["Complete set", "High-quality bristles", "Ergonomic handles", "Professional grade", "Durable"],
    isFeatured: true,
  },
  {
    title: "Long-Lasting Liquid Lipstick",
    description: "Vibrant liquid lipstick with 12-hour wear time. Available in multiple shades with comfortable formula.",
    category: "Beauty & Personal Care",
    subcategory: "Makeup",
    brand: "LipColor",
    imageUrl: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800&h=800&fit=crop&q=80",
    price: "16.99",
    originalPrice: "24.99",
    currency: "GBP",
    rating: "4.5",
    reviewCount: 1567,
    availability: "in_stock",
    stockQuantity: 212,
    features: ["12-hour wear", "Vibrant colors", "Comfortable formula", "Multiple shades", "Quick dry"],
    isFeatured: false,
  },
  {
    title: "Powder Makeup Foundation",
    description: "Full-coverage powder foundation for flawless complexion. Blends smoothly and lasts all day with comfortable wear.",
    category: "Beauty & Personal Care",
    subcategory: "Makeup",
    brand: "FoundationMax",
    imageUrl: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800&h=800&fit=crop&q=80",
    price: "29.99",
    originalPrice: "39.99",
    currency: "GBP",
    rating: "4.6",
    reviewCount: 1345,
    availability: "in_stock",
    stockQuantity: 134,
    features: ["Full coverage", "Smooth blending", "All-day wear", "Multiple shades", "Comfortable"],
    isFeatured: false,
  },
  {
    title: "Designer Fragrance Perfume",
    description: "Luxurious fragrance with sophisticated blend of notes. Long-lasting scent perfect for special occasions and everyday wear.",
    category: "Beauty & Personal Care",
    subcategory: "Fragrance",
    brand: "FragranceLux",
    imageUrl: "https://images.unsplash.com/photo-1541643600914-985686d1e80a?w=800&h=800&fit=crop&q=80",
    price: "79.99",
    originalPrice: "119.99",
    currency: "GBP",
    rating: "4.8",
    reviewCount: 678,
    availability: "in_stock",
    stockQuantity: 45,
    features: ["Sophisticated blend", "Long-lasting", "Luxury fragrance", "Special occasions", "Premium bottle"],
    isFeatured: true,
  },
  {
    title: "Casual Cologne for Men",
    description: "Fresh and energizing cologne perfect for everyday wear. Light and pleasant scent ideal for casual occasions.",
    category: "Beauty & Personal Care",
    subcategory: "Fragrance",
    brand: "CasualScent",
    imageUrl: "https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?w=800&h=800&fit=crop&q=80",
    price: "39.99",
    originalPrice: "59.99",
    currency: "GBP",
    rating: "4.5",
    reviewCount: 834,
    availability: "in_stock",
    stockQuantity: 98,
    features: ["Fresh scent", "Everyday wear", "Light fragrance", "Long-lasting", "Casual style"],
    isFeatured: false,
  },
  {
    title: "Moisturizing Lip Balm",
    description: "Nourishing lip balm with natural ingredients. Keeps lips soft and protected throughout the day.",
    category: "Beauty & Personal Care",
    subcategory: "Skincare",
    brand: "LipCare",
    imageUrl: "https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=800&h=800&fit=crop&q=80",
    price: "12.99",
    originalPrice: "18.99",
    currency: "GBP",
    rating: "4.6",
    reviewCount: 2341,
    availability: "in_stock",
    stockQuantity: 267,
    features: ["Natural ingredients", "Moisturizing", "Long-lasting", "Daily protection", "Lightweight"],
    isFeatured: false,
  },
  {
    title: "Deep Conditioning Hair Treatment",
    description: "Intensive hair treatment for damaged and dry hair. Restores health and shine with regular use.",
    category: "Beauty & Personal Care",
    subcategory: "Haircare",
    brand: "HairRepair",
    imageUrl: "https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?w=800&h=800&fit=crop&q=80",
    price: "27.99",
    originalPrice: "39.99",
    currency: "GBP",
    rating: "4.7",
    reviewCount: 1123,
    availability: "in_stock",
    stockQuantity: 123,
    features: ["Intensive treatment", "Damaged hair repair", "Shine restoring", "Weekly use", "Effective"],
    isFeatured: true,
  },
  {
    title: "Eye Shadow Palette",
    description: "Versatile eye shadow palette with multiple colors and finishes. Perfect for creating various makeup looks.",
    category: "Beauty & Personal Care",
    subcategory: "Makeup",
    brand: "EyeColor",
    imageUrl: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800&h=800&fit=crop&q=80",
    price: "34.99",
    originalPrice: "49.99",
    currency: "GBP",
    rating: "4.6",
    reviewCount: 1456,
    availability: "in_stock",
    stockQuantity: 145,
    features: ["Multiple colors", "Various finishes", "Blendable", "Long-lasting", "Versatile looks"],
    isFeatured: false,
  },
  {
    title: "Waterproof Mascara",
    description: "Long-wearing waterproof mascara for defined lashes. Perfect for all-day wear and water activities.",
    category: "Beauty & Personal Care",
    subcategory: "Makeup",
    brand: "LashMax",
    imageUrl: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800&h=800&fit=crop&q=80",
    price: "21.99",
    originalPrice: "31.99",
    currency: "GBP",
    rating: "4.7",
    reviewCount: 1834,
    availability: "in_stock",
    stockQuantity: 178,
    features: ["Waterproof formula", "Long-lasting", "Defined lashes", "All-day wear", "Easy removal"],
    isFeatured: false,
  },

  // Books & Media - 12 products
  {
    title: "Modern Fiction Novel",
    description: "Contemporary bestselling novel with compelling narrative and character development. Perfect for book lovers seeking engaging stories.",
    category: "Books & Media",
    subcategory: "Fiction",
    brand: "PublishPress",
    imageUrl: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800&h=800&fit=crop&q=80",
    price: "14.99",
    originalPrice: "19.99",
    currency: "GBP",
    rating: "4.7",
    reviewCount: 2145,
    availability: "in_stock",
    stockQuantity: 145,
    features: ["Bestselling author", "Engaging narrative", "Character development", "Hardcover edition", "Award-winning"],
    isFeatured: true,
  },
  {
    title: "Science & Technology Non-Fiction",
    description: "Informative book exploring cutting-edge science and technology. Perfect for curious minds interested in innovation and discovery.",
    category: "Books & Media",
    subcategory: "Non-Fiction",
    brand: "TechPress",
    imageUrl: "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=800&h=800&fit=crop&q=80",
    price: "18.99",
    originalPrice: "24.99",
    currency: "GBP",
    rating: "4.6",
    reviewCount: 1456,
    availability: "in_stock",
    stockQuantity: 98,
    features: ["Well-researched", "Innovation focus", "Expert author", "Illustrated", "Thought-provoking"],
    isFeatured: false,
  },
  {
    title: "Programming Technology Guide",
    description: "Comprehensive programming guide with practical examples and tutorials. Essential resource for developers of all levels.",
    category: "Books & Media",
    subcategory: "Tech Books",
    brand: "CodePress",
    imageUrl: "https://images.unsplash.com/photo-1524578271613-d550eacf6090?w=800&h=800&fit=crop&q=80",
    price: "39.99",
    originalPrice: "49.99",
    currency: "GBP",
    rating: "4.8",
    reviewCount: 834,
    availability: "in_stock",
    stockQuantity: 56,
    features: ["Practical examples", "Code tutorials", "All skill levels", "Updated content", "Clear explanations"],
    isFeatured: true,
  },
  {
    title: "Self-Help Development Book",
    description: "Inspiring self-improvement book with practical strategies for personal growth. Perfect for motivation and life transformation.",
    category: "Books & Media",
    subcategory: "Non-Fiction",
    brand: "LifePress",
    imageUrl: "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=800&h=800&fit=crop&q=80",
    price: "16.99",
    originalPrice: "22.99",
    currency: "GBP",
    rating: "4.5",
    reviewCount: 1567,
    availability: "in_stock",
    stockQuantity: 123,
    features: ["Practical strategies", "Personal growth", "Motivating", "Real examples", "Actionable advice"],
    isFeatured: false,
  },
  {
    title: "Digital Audio Book Fiction",
    description: "Bestselling fiction narrated by professional voice actors. Enjoy immersive storytelling through digital audio format.",
    category: "Books & Media",
    subcategory: "Audiobooks",
    brand: "AudioPress",
    imageUrl: "https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=800&h=800&fit=crop&q=80",
    price: "12.99",
    originalPrice: "18.99",
    currency: "GBP",
    rating: "4.6",
    reviewCount: 892,
    availability: "in_stock",
    stockQuantity: 234,
    features: ["Professional narration", "Immersive", "Digital format", "Bestseller", "High quality audio"],
    isFeatured: false,
  },
  {
    title: "Fantasy Adventure Series",
    description: "Epic fantasy novel with rich world-building and compelling characters. First in popular series perfect for fantasy enthusiasts.",
    category: "Books & Media",
    subcategory: "Fiction",
    brand: "FantasyPress",
    imageUrl: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800&h=800&fit=crop&q=80",
    price: "15.99",
    originalPrice: "21.99",
    currency: "GBP",
    rating: "4.8",
    reviewCount: 2345,
    availability: "in_stock",
    stockQuantity: 167,
    features: ["Epic world-building", "Compelling characters", "Series starter", "Bestseller", "Immersive story"],
    isFeatured: true,
  },
  {
    title: "History & Culture Book",
    description: "Fascinating exploration of history and cultural heritage. Well-researched and engaging for history enthusiasts.",
    category: "Books & Media",
    subcategory: "Non-Fiction",
    brand: "HistoryPress",
    imageUrl: "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=800&h=800&fit=crop&q=80",
    price: "19.99",
    originalPrice: "26.99",
    currency: "GBP",
    rating: "4.7",
    reviewCount: 1123,
    availability: "in_stock",
    stockQuantity: 89,
    features: ["Well-researched", "Engaging narrative", "Cultural insights", "Illustrated", "Award-winning"],
    isFeatured: false,
  },
  {
    title: "Mystery Thriller Novel",
    description: "Gripping mystery with unexpected twists and complex plot. Perfect for thriller enthusiasts who enjoy suspenseful stories.",
    category: "Books & Media",
    subcategory: "Fiction",
    brand: "ThrillerPress",
    imageUrl: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800&h=800&fit=crop&q=80",
    price: "13.99",
    originalPrice: "18.99",
    currency: "GBP",
    rating: "4.6",
    reviewCount: 1678,
    availability: "in_stock",
    stockQuantity: 145,
    features: ["Gripping plot", "Unexpected twists", "Suspenseful", "Page-turner", "Complex mystery"],
    isFeatured: false,
  },
  {
    title: "Business Strategy Guide",
    description: "Comprehensive business strategy book with real-world examples. Essential reading for entrepreneurs and business leaders.",
    category: "Books & Media",
    subcategory: "Non-Fiction",
    brand: "BusinessPress",
    imageUrl: "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=800&h=800&fit=crop&q=80",
    price: "24.99",
    originalPrice: "34.99",
    currency: "GBP",
    rating: "4.7",
    reviewCount: 945,
    availability: "in_stock",
    stockQuantity: 67,
    features: ["Real-world examples", "Practical strategies", "For entrepreneurs", "Expert insights", "Comprehensive"],
    isFeatured: true,
  },
  {
    title: "Cooking & Recipe Book",
    description: "Delicious recipes from renowned chef with step-by-step instructions. Perfect for home cooks of all skill levels.",
    category: "Books & Media",
    subcategory: "Non-Fiction",
    brand: "CookPress",
    imageUrl: "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=800&h=800&fit=crop&q=80",
    price: "21.99",
    originalPrice: "31.99",
    currency: "GBP",
    rating: "4.5",
    reviewCount: 1234,
    availability: "in_stock",
    stockQuantity: 112,
    features: ["Chef recipes", "Step-by-step", "Beautiful photos", "All skill levels", "Professional"],
    isFeatured: false,
  },
  {
    title: "Art & Design Coffee Table Book",
    description: "Stunning visual art book showcasing contemporary and classic designs. Perfect for art lovers and home decoration.",
    category: "Books & Media",
    subcategory: "Non-Fiction",
    brand: "ArtPress",
    imageUrl: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&h=800&fit=crop&q=80",
    price: "34.99",
    originalPrice: "49.99",
    currency: "GBP",
    rating: "4.8",
    reviewCount: 567,
    availability: "in_stock",
    stockQuantity: 45,
    features: ["Stunning visuals", "Contemporary art", "Coffee table worthy", "High quality print", "Inspiring"],
    isFeatured: true,
  },

  // Toys & Games - 12 products
  {
    title: "Family Board Game Collection",
    description: "Classic board game perfect for family gatherings and parties. Features simple rules, exciting gameplay, and fun for all ages.",
    category: "Toys & Games",
    subcategory: "Board Games",
    brand: "GameCo",
    imageUrl: "https://images.unsplash.com/photo-1558060169-a2a3a0b2e0e0?w=800&h=800&fit=crop&q=80",
    price: "29.99",
    originalPrice: "39.99",
    currency: "GBP",
    rating: "4.7",
    reviewCount: 1567,
    availability: "in_stock",
    stockQuantity: 145,
    features: ["Family-friendly", "Simple rules", "Fun gameplay", "For all ages", "Durable components"],
    isFeatured: true,
  },
  {
    title: "Strategic Card Game",
    description: "Strategic card game requiring planning and tactical thinking. Perfect for experienced gamers looking for challenging gameplay.",
    category: "Toys & Games",
    subcategory: "Games",
    brand: "StrategyGames",
    imageUrl: "https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=800&h=800&fit=crop&q=80",
    price: "24.99",
    originalPrice: "34.99",
    currency: "GBP",
    rating: "4.8",
    reviewCount: 892,
    availability: "in_stock",
    stockQuantity: 89,
    features: ["Strategic gameplay", "Tactical thinking", "Experienced players", "Replayable", "Complex rules"],
    isFeatured: false,
  },
  {
    title: "3D Puzzle Challenge Set",
    description: "Complex 3D puzzle with hundreds of pieces. Perfect brain-teaser activity for puzzle enthusiasts of all levels.",
    category: "Toys & Games",
    subcategory: "Puzzles",
    brand: "PuzzleMax",
    imageUrl: "https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=800&h=800&fit=crop&q=80",
    price: "34.99",
    originalPrice: "49.99",
    currency: "GBP",
    rating: "4.6",
    reviewCount: 1234,
    availability: "in_stock",
    stockQuantity: 67,
    features: ["3D structure", "Hundreds of pieces", "Brain challenge", "All skill levels", "Quality pieces"],
    isFeatured: true,
  },
  {
    title: "STEM Educational Robotics Kit",
    description: "Hands-on learning kit teaching robotics and programming. Perfect educational toy for curious kids interested in technology.",
    category: "Toys & Games",
    subcategory: "Educational",
    brand: "RoboLearning",
    imageUrl: "https://images.unsplash.com/photo-1606503153255-59d5a1a0d2c2?w=800&h=800&fit=crop&q=80",
    price: "79.99",
    originalPrice: "119.99",
    currency: "GBP",
    rating: "4.8",
    reviewCount: 1456,
    availability: "in_stock",
    stockQuantity: 45,
    features: ["STEM learning", "Robotics", "Programming basics", "Interactive", "Hands-on"],
    isFeatured: true,
  },
  {
    title: "Outdoor Adventure Toy Set",
    description: "Complete outdoor play set with multiple accessories. Perfect for outdoor games and garden adventures.",
    category: "Toys & Games",
    subcategory: "Outdoor Toys",
    brand: "OutdoorPlay",
    imageUrl: "https://images.unsplash.com/photo-1494059980-2f76eada72f2?w=800&h=800&fit=crop&q=80",
    price: "49.99",
    originalPrice: "69.99",
    currency: "GBP",
    rating: "4.5",
    reviewCount: 1023,
    availability: "in_stock",
    stockQuantity: 78,
    features: ["Multiple accessories", "Outdoor games", "Adventure play", "Durable", "Safety tested"],
    isFeatured: false,
  },
  {
    title: "Building Block System",
    description: "Expandable building system with hundreds of colorful blocks. Encourages creativity and spatial understanding for young builders.",
    category: "Toys & Games",
    subcategory: "Educational",
    brand: "BuildBlocks",
    imageUrl: "https://images.unsplash.com/photo-1516110833967-0b5716ca1387?w=800&h=800&fit=crop&q=80",
    price: "39.99",
    originalPrice: "54.99",
    currency: "GBP",
    rating: "4.7",
    reviewCount: 1789,
    availability: "in_stock",
    stockQuantity: 123,
    features: ["Hundreds of blocks", "Expandable system", "Creativity building", "Spatial learning", "Safe materials"],
    isFeatured: false,
  },
  {
    title: "Jigsaw Puzzle 1000 Pieces",
    description: "Classic jigsaw puzzle with beautiful scenic design. Perfect relaxing activity with quality pieces and detailed image.",
    category: "Toys & Games",
    subcategory: "Puzzles",
    brand: "JigsawMax",
    imageUrl: "https://images.unsplash.com/photo-1494059980-2f76eada72f2?w=800&h=800&fit=crop&q=80",
    price: "19.99",
    originalPrice: "27.99",
    currency: "GBP",
    rating: "4.6",
    reviewCount: 1245,
    availability: "in_stock",
    stockQuantity: 156,
    features: ["1000 pieces", "Beautiful design", "Quality pieces", "Relaxing activity", "Detailed image"],
    isFeatured: false,
  },
  {
    title: "Board Game Collection",
    description: "Set of multiple popular board games in one package. Great value for game night enthusiasts with variety.",
    category: "Toys & Games",
    subcategory: "Board Games",
    brand: "GameBundle",
    imageUrl: "https://images.unsplash.com/photo-1558060169-a2a3a0b2e0e0?w=800&h=800&fit=crop&q=80",
    price: "59.99",
    originalPrice: "84.99",
    currency: "GBP",
    rating: "4.5",
    reviewCount: 892,
    availability: "in_stock",
    stockQuantity: 45,
    features: ["Multiple games", "Great value", "Popular titles", "Variety", "Family fun"],
    isFeatured: false,
  },
  {
    title: "Action Figure Collection",
    description: "Collectible action figures with detailed design and articulation. Perfect for collectors and toy enthusiasts.",
    category: "Toys & Games",
    subcategory: "Outdoor Toys",
    brand: "ActionMax",
    imageUrl: "https://images.unsplash.com/photo-1606503153255-59d5a1a0d2c2?w=800&h=800&fit=crop&q=80",
    price: "29.99",
    originalPrice: "39.99",
    currency: "GBP",
    rating: "4.6",
    reviewCount: 1567,
    availability: "in_stock",
    stockQuantity: 134,
    features: ["Detailed design", "Articulated", "Collectible", "Display quality", "Durable"],
    isFeatured: false,
  },
  {
    title: "Educational Science Kit",
    description: "Hands-on science learning kit with multiple experiments. Perfect for curious kids exploring scientific concepts.",
    category: "Toys & Games",
    subcategory: "Educational",
    brand: "ScienceKids",
    imageUrl: "https://images.unsplash.com/photo-1606503153255-59d5a1a0d2c2?w=800&h=800&fit=crop&q=80",
    price: "34.99",
    originalPrice: "49.99",
    currency: "GBP",
    rating: "4.7",
    reviewCount: 1234,
    availability: "in_stock",
    stockQuantity: 98,
    features: ["Multiple experiments", "Science learning", "Hands-on", "Safety tested", "Detailed guide"],
    isFeatured: true,
  },
  {
    title: "Inflatable Outdoor Games",
    description: "Set of inflatable outdoor games perfect for summer parties and gatherings. Includes pumps and repair kit.",
    category: "Toys & Games",
    subcategory: "Outdoor Toys",
    brand: "OutdoorFun",
    imageUrl: "https://images.unsplash.com/photo-1494059980-2f76eada72f2?w=800&h=800&fit=crop&q=80",
    price: "44.99",
    originalPrice: "64.99",
    currency: "GBP",
    rating: "4.5",
    reviewCount: 1123,
    availability: "in_stock",
    stockQuantity: 67,
    features: ["Multiple games", "Inflatable set", "Party ready", "Repair kit included", "Durable material"],
    isFeatured: false,
  },

  // Food & Beverages - 12 products
  {
    title: "Premium Gourmet Coffee Beans",
    description: "Single-origin specialty coffee beans with rich flavor profile. Perfect for coffee enthusiasts seeking premium quality.",
    category: "Food & Beverages",
    subcategory: "Beverages",
    brand: "CoffeeLux",
    imageUrl: "https://images.unsplash.com/photo-1490818387583-1bc5681bfd95?w=800&h=800&fit=crop&q=80",
    price: "24.99",
    originalPrice: "34.99",
    currency: "GBP",
    rating: "4.8",
    reviewCount: 1567,
    availability: "in_stock",
    stockQuantity: 156,
    features: ["Single-origin", "Premium quality", "Rich flavor", "Specialty grade", "Freshly roasted"],
    isFeatured: true,
  },
  {
    title: "Organic Tea Collection",
    description: "Assorted organic tea selection with multiple flavors. Perfect for tea lovers preferring natural and healthy options.",
    category: "Food & Beverages",
    subcategory: "Beverages",
    brand: "TeaNature",
    imageUrl: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&h=800&fit=crop&q=80",
    price: "19.99",
    originalPrice: "29.99",
    currency: "GBP",
    rating: "4.6",
    reviewCount: 1234,
    availability: "in_stock",
    stockQuantity: 145,
    features: ["Organic certified", "Multiple flavors", "Natural ingredients", "Health-focused", "Premium quality"],
    isFeatured: false,
  },
  {
    title: "Artisan Chocolate Gift Box",
    description: "Premium assorted chocolates in elegant gift box. Perfect for gifting with handcrafted quality and luxurious flavors.",
    category: "Food & Beverages",
    subcategory: "Gourmet",
    brand: "ChocolateLux",
    imageUrl: "https://images.unsplash.com/photo-1499028344343-cd173ffc68a9?w=800&h=800&fit=crop&q=80",
    price: "39.99",
    originalPrice: "54.99",
    currency: "GBP",
    rating: "4.8",
    reviewCount: 892,
    availability: "in_stock",
    stockQuantity: 67,
    features: ["Premium chocolate", "Artisan crafted", "Elegant gift box", "Multiple flavors", "Luxury quality"],
    isFeatured: true,
  },
  {
    title: "Organic Raw Honey",
    description: "Pure raw honey with no additives or processing. Perfect natural sweetener with health benefits.",
    category: "Food & Beverages",
    subcategory: "Gourmet",
    brand: "NatureHoney",
    imageUrl: "https://images.unsplash.com/photo-1490818387583-1bc5681bfd95?w=800&h=800&fit=crop&q=80",
    price: "14.99",
    originalPrice: "19.99",
    currency: "GBP",
    rating: "4.7",
    reviewCount: 1456,
    availability: "in_stock",
    stockQuantity: 189,
    features: ["Raw & pure", "No additives", "Natural sweetener", "Health benefits", "Organic sourced"],
    isFeatured: false,
  },
  {
    title: "Gourmet Nuts & Dried Fruits Mix",
    description: "Premium assortment of roasted nuts and dried fruits. Healthy snack perfect for office and travel.",
    category: "Food & Beverages",
    subcategory: "Snacks",
    brand: "NutsMix",
    imageUrl: "https://images.unsplash.com/photo-1544145945-f90425340c7e?w=800&h=800&fit=crop&q=80",
    price: "16.99",
    originalPrice: "24.99",
    currency: "GBP",
    rating: "4.6",
    reviewCount: 1234,
    availability: "in_stock",
    stockQuantity: 123,
    features: ["Premium quality", "Multiple varieties", "Roasted perfectly", "Healthy snack", "Travel-friendly"],
    isFeatured: false,
  },
  {
    title: "Exotic Spice Collection",
    description: "Rare and exotic spices collection for culinary adventures. Perfect for adventurous cooks seeking unique flavors.",
    category: "Food & Beverages",
    subcategory: "Gourmet",
    brand: "SpiceWorld",
    imageUrl: "https://images.unsplash.com/photo-1497534446932-c925b458314e?w=800&h=800&fit=crop&q=80",
    price: "34.99",
    originalPrice: "49.99",
    currency: "GBP",
    rating: "4.7",
    reviewCount: 789,
    availability: "in_stock",
    stockQuantity: 45,
    features: ["Rare spices", "Exotic flavors", "Premium quality", "Culinary adventures", "Fresh packed"],
    isFeatured: true,
  },
  {
    title: "Premium Olive Oil",
    description: "Extra virgin olive oil from Mediterranean vineyards. Perfect for cooking and salad dressing with authentic flavor.",
    category: "Food & Beverages",
    subcategory: "Gourmet",
    brand: "OliveMed",
    imageUrl: "https://images.unsplash.com/photo-1544145945-f90425340c7e?w=800&h=800&fit=crop&q=80",
    price: "21.99",
    originalPrice: "31.99",
    currency: "GBP",
    rating: "4.8",
    reviewCount: 1456,
    availability: "in_stock",
    stockQuantity: 98,
    features: ["Extra virgin", "Mediterranean", "Authentic flavor", "Cooking & salads", "Premium quality"],
    isFeatured: false,
  },
  {
    title: "Organic Superfood Powder",
    description: "Nutrient-dense superfood powder for smoothies and beverages. Perfect health supplement for active lifestyles.",
    category: "Food & Beverages",
    subcategory: "Beverages",
    brand: "SuperHealth",
    imageUrl: "https://images.unsplash.com/photo-1497534446932-c925b458314e?w=800&h=800&fit=crop&q=80",
    price: "27.99",
    originalPrice: "39.99",
    currency: "GBP",
    rating: "4.6",
    reviewCount: 1123,
    availability: "in_stock",
    stockQuantity: 134,
    features: ["Organic certified", "Nutrient-dense", "Superfood blend", "Smooth mixing", "Health supplement"],
    isFeatured: true,
  },
  {
    title: "Gourmet Pasta Selection",
    description: "Premium Italian pasta with traditional shapes and flavors. Perfect for authentic Italian cooking.",
    category: "Food & Beverages",
    subcategory: "Gourmet",
    brand: "PastaItalian",
    imageUrl: "https://images.unsplash.com/photo-1544145945-f90425340c7e?w=800&h=800&fit=crop&q=80",
    price: "12.99",
    originalPrice: "18.99",
    currency: "GBP",
    rating: "4.5",
    reviewCount: 1234,
    availability: "in_stock",
    stockQuantity: 178,
    features: ["Italian import", "Traditional shapes", "Premium quality", "Authentic taste", "Multiple varieties"],
    isFeatured: false,
  },
  {
    title: "Organic Snack Bars",
    description: "Healthy snack bars made with organic ingredients. Perfect for quick energy without artificial additives.",
    category: "Food & Beverages",
    subcategory: "Snacks",
    brand: "HealthyBars",
    imageUrl: "https://images.unsplash.com/photo-1621939514649-280e2ee25f60?w=800&h=800&fit=crop&q=80",
    price: "14.99",
    originalPrice: "21.99",
    currency: "GBP",
    rating: "4.5",
    reviewCount: 1567,
    availability: "in_stock",
    stockQuantity: 212,
    features: ["Organic ingredients", "No artificial additives", "Healthy snack", "Quick energy", "Portable"],
    isFeatured: false,
  },
  {
    title: "Craft Beverage Collection",
    description: "Assorted craft beverages including sodas and juices. Perfect for variety seekers enjoying premium tastes.",
    category: "Food & Beverages",
    subcategory: "Beverages",
    brand: "CraftBev",
    imageUrl: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=800&h=800&fit=crop&q=80",
    price: "18.99",
    originalPrice: "27.99",
    currency: "GBP",
    rating: "4.6",
    reviewCount: 1245,
    availability: "in_stock",
    stockQuantity: 145,
    features: ["Craft quality", "Multiple flavors", "Premium ingredients", "Natural flavors", "Variety pack"],
    isFeatured: false,
  },

  // Office & Stationery - 12 products
  {
    title: "Ergonomic Desk Organizer",
    description: "Smart desk organizer with multiple compartments for office essentials. Perfect for keeping workspace tidy and organized.",
    category: "Office & Stationery",
    subcategory: "Desk Accessories",
    brand: "DeskPro",
    imageUrl: "https://images.unsplash.com/photo-1507925921958-8a62f3d1a50d?w=800&h=800&fit=crop&q=80",
    price: "34.99",
    originalPrice: "49.99",
    currency: "GBP",
    rating: "4.7",
    reviewCount: 1567,
    availability: "in_stock",
    stockQuantity: 134,
    features: ["Multiple compartments", "Smart design", "Durable material", "Space-saving", "Professional look"],
    isFeatured: false,
  },
  {
    title: "Premium Pen Set",
    description: "Luxury writing pen collection with smooth writing experience. Perfect for professionals and pen enthusiasts.",
    category: "Office & Stationery",
    subcategory: "Pens",
    brand: "WritePro",
    imageUrl: "https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=800&h=800&fit=crop&q=80",
    price: "29.99",
    originalPrice: "39.99",
    currency: "GBP",
    rating: "4.6",
    reviewCount: 1234,
    availability: "in_stock",
    stockQuantity: 145,
    features: ["Luxury writing", "Smooth ink", "Professional grade", "Multiple colors", "Durable"],
    isFeatured: true,
  },
  {
    title: "Annual Planning Planner",
    description: "Comprehensive yearly planner with monthly and weekly layouts. Perfect for organization and goal tracking.",
    category: "Office & Stationery",
    subcategory: "Planners",
    brand: "PlanMax",
    imageUrl: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&h=800&fit=crop&q=80",
    price: "24.99",
    originalPrice: "34.99",
    currency: "GBP",
    rating: "4.5",
    reviewCount: 1456,
    availability: "in_stock",
    stockQuantity: 123,
    features: ["Yearly layout", "Monthly & weekly", "Goal tracking", "Quality paper", "Professional design"],
    isFeatured: false,
  },
  {
    title: "Colorful Notebook Collection",
    description: "Set of vibrant notebooks for notes and ideas. Perfect for creative writing and brainstorming.",
    category: "Office & Stationery",
    subcategory: "Organizers",
    brand: "NotebookMax",
    imageUrl: "https://images.unsplash.com/photo-1456735190827-d1262f71b8a3?w=800&h=800&fit=crop&q=80",
    price: "19.99",
    originalPrice: "29.99",
    currency: "GBP",
    rating: "4.6",
    reviewCount: 1123,
    availability: "in_stock",
    stockQuantity: 167,
    features: ["Vibrant colors", "Quality paper", "Multiple sizes", "Creative friendly", "Durable binding"],
    isFeatured: false,
  },
  {
    title: "File Organization System",
    description: "Complete filing system with folders and labels. Perfect for document management and office organization.",
    category: "Office & Stationery",
    subcategory: "Organizers",
    brand: "FilePro",
    imageUrl: "https://images.unsplash.com/photo-1484101403633-562f891dc89a?w=800&h=800&fit=crop&q=80",
    price: "39.99",
    originalPrice: "54.99",
    currency: "GBP",
    rating: "4.7",
    reviewCount: 892,
    availability: "in_stock",
    stockQuantity: 89,
    features: ["Complete system", "Multiple folders", "Label included", "Organization ready", "Durable"],
    isFeatured: true,
  },
  {
    title: "Desk Lamp with USB Charging",
    description: "Modern desk lamp with integrated USB charging port. Perfect for productive workspace with convenient charging.",
    category: "Office & Stationery",
    subcategory: "Desk Accessories",
    brand: "LampTech",
    imageUrl: "https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=800&h=800&fit=crop&q=80",
    price: "34.99",
    originalPrice: "49.99",
    currency: "GBP",
    rating: "4.6",
    reviewCount: 1345,
    availability: "in_stock",
    stockQuantity: 112,
    features: ["USB charging", "Modern design", "Bright LED", "Adjustable", "Energy efficient"],
    isFeatured: false,
  },
  {
    title: "Sticky Notes Variety Pack",
    description: "Assorted sticky notes in multiple colors and sizes. Essential office supplies for notes and reminders.",
    category: "Office & Stationery",
    subcategory: "Stationery",
    brand: "NoteSticky",
    imageUrl: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&h=800&fit=crop&q=80",
    price: "9.99",
    originalPrice: "14.99",
    currency: "GBP",
    rating: "4.5",
    reviewCount: 2341,
    availability: "in_stock",
    stockQuantity: 345,
    features: ["Multiple colors", "Various sizes", "Adhesive strong", "Eco-friendly", "Office essential"],
    isFeatured: false,
  },
  {
    title: "Professional Stapler Set",
    description: "Heavy-duty stapler with staples and remover. Perfect for office work with reliable performance.",
    category: "Office & Stationery",
    subcategory: "Desk Accessories",
    brand: "StaplePro",
    imageUrl: "https://images.unsplash.com/photo-1507925921958-8a62f3d1a50d?w=800&h=800&fit=crop&q=80",
    price: "16.99",
    originalPrice: "24.99",
    currency: "GBP",
    rating: "4.5",
    reviewCount: 1023,
    availability: "in_stock",
    stockQuantity: 178,
    features: ["Heavy-duty", "Reliable performance", "Staples included", "Remover tool", "Professional"],
    isFeatured: false,
  },
  {
    title: "Desk Calendar Organizer",
    description: "Desktop calendar with daily planning grid. Perfect for daily scheduling and office organization.",
    category: "Office & Stationery",
    subcategory: "Planners",
    brand: "CalendarPro",
    imageUrl: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&h=800&fit=crop&q=80",
    price: "21.99",
    originalPrice: "31.99",
    currency: "GBP",
    rating: "4.6",
    reviewCount: 1234,
    availability: "in_stock",
    stockQuantity: 145,
    features: ["Daily grid", "Desktop display", "Planning friendly", "Quality material", "Professional design"],
    isFeatured: false,
  },
  {
    title: "Portable Document Holder",
    description: "Compact document organizer for mobile professionals. Perfect for carrying important papers.",
    category: "Office & Stationery",
    subcategory: "Organizers",
    brand: "PortableDoc",
    imageUrl: "https://images.unsplash.com/photo-1484101403633-562f891dc89a?w=800&h=800&fit=crop&q=80",
    price: "19.99",
    originalPrice: "29.99",
    currency: "GBP",
    rating: "4.5",
    reviewCount: 789,
    availability: "in_stock",
    stockQuantity: 134,
    features: ["Portable design", "Compact size", "Secure closure", "Professional look", "Durable material"],
    isFeatured: false,
  },
  {
    title: "Highlighter Pen Collection",
    description: "Vibrant highlighter set with multiple neon colors. Perfect for marking important text and organization.",
    category: "Office & Stationery",
    subcategory: "Pens",
    brand: "HighlightPro",
    imageUrl: "https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=800&h=800&fit=crop&q=80",
    price: "12.99",
    originalPrice: "18.99",
    currency: "GBP",
    rating: "4.6",
    reviewCount: 1567,
    availability: "in_stock",
    stockQuantity: 234,
    features: ["Neon colors", "Vibrant ink", "Smooth marking", "Multiple colors", "Professional grade"],
    isFeatured: false,
  },

  // Pet Supplies - 6 products
  {
    title: "Premium Dog Food",
    description: "Nutritionally balanced dog food with natural ingredients. Supports healthy coat and energy levels for active dogs.",
    category: "Pet Supplies",
    subcategory: "Dog",
    brand: "DogNutrition",
    imageUrl: "https://images.unsplash.com/photo-1450778869180-e68d45a97ac7?w=800&h=800&fit=crop&q=80",
    price: "29.99",
    originalPrice: "39.99",
    currency: "GBP",
    rating: "4.7",
    reviewCount: 1567,
    availability: "in_stock",
    stockQuantity: 156,
    features: ["Natural ingredients", "Nutritionally balanced", "Healthy coat", "Energy support", "Premium quality"],
    isFeatured: true,
  },
  {
    title: "Cat Litter Box with Odor Control",
    description: "Modern litter box featuring excellent odor control and easy cleaning. Perfect for indoor cats with hygienic design.",
    category: "Pet Supplies",
    subcategory: "Cat",
    brand: "CatHome",
    imageUrl: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=800&h=800&fit=crop&q=80",
    price: "34.99",
    originalPrice: "49.99",
    currency: "GBP",
    rating: "4.5",
    reviewCount: 1234,
    availability: "in_stock",
    stockQuantity: 89,
    features: ["Odor control", "Easy cleaning", "Modern design", "Hygienic", "Spacious"],
    isFeatured: false,
  },
  {
    title: "Interactive Dog Toy Set",
    description: "Engaging toy set for mental stimulation and play. Keeps dogs entertained with multiple interactive features.",
    category: "Pet Supplies",
    subcategory: "Accessories",
    brand: "DogPlay",
    imageUrl: "https://images.unsplash.com/photo-1583511655826-05700d52f51d?w=800&h=800&fit=crop&q=80",
    price: "24.99",
    originalPrice: "34.99",
    currency: "GBP",
    rating: "4.6",
    reviewCount: 1456,
    availability: "in_stock",
    stockQuantity: 123,
    features: ["Mental stimulation", "Interactive features", "Durable design", "Multiple toys", "Safe materials"],
    isFeatured: false,
  },
  {
    title: "Premium Cat Food",
    description: "High-quality cat food with essential nutrients and vitamins. Supports urinary health and optimal weight management.",
    category: "Pet Supplies",
    subcategory: "Cat",
    brand: "CatNutrition",
    imageUrl: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=800&h=800&fit=crop&q=80",
    price: "21.99",
    originalPrice: "31.99",
    currency: "GBP",
    rating: "4.7",
    reviewCount: 1123,
    availability: "in_stock",
    stockQuantity: 145,
    features: ["Essential nutrients", "Urinary health", "Weight management", "Natural ingredients", "Premium quality"],
    isFeatured: true,
  },
  {
    title: "Adjustable Pet Collar and Leash",
    description: "Durable and comfortable collar and leash set. Perfect for walks with adjustable fit and secure buckles.",
    category: "Pet Supplies",
    subcategory: "Accessories",
    brand: "PetGear",
    imageUrl: "https://images.unsplash.com/photo-1583511655826-05700d52f51d?w=800&h=800&fit=crop&q=80",
    price: "19.99",
    originalPrice: "29.99",
    currency: "GBP",
    rating: "4.5",
    reviewCount: 1345,
    availability: "in_stock",
    stockQuantity: 178,
    features: ["Adjustable fit", "Secure buckles", "Comfortable design", "Durable material", "Multiple sizes"],
    isFeatured: false,
  },
  {
    title: "Cozy Pet Bed",
    description: "Comfortable cushioned pet bed perfect for sleeping and rest. Features washable cover and supportive padding.",
    category: "Pet Supplies",
    subcategory: "Accessories",
    brand: "ComfyPet",
    imageUrl: "https://images.unsplash.com/photo-1583511655826-05700d52f51d?w=800&h=800&fit=crop&q=80",
    price: "39.99",
    originalPrice: "54.99",
    currency: "GBP",
    rating: "4.8",
    reviewCount: 1234,
    availability: "in_stock",
    stockQuantity: 67,
    features: ["Comfortable cushion", "Washable cover", "Supportive padding", "Cozy design", "Multiple sizes"],
    isFeatured: true,
  },
];
